eco_harvester:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      threads: 1
      extensions:
        - httpfs
      settings:
        s3_endpoint: "{{ env_var('MINIO_ENDPOINT_LOCAL', env_var('MINIO_ENDPOINT')) }}"
        s3_access_key_id: "{{ env_var('MINIO_ROOT_USER') }}"
        s3_secret_access_key: "{{ env_var('MINIO_ROOT_PASSWORD') }}"
        s3_use_ssl: false
        s3_url_style: path

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4
      extensions:
        - httpfs
      settings:
        s3_endpoint: "{{ env_var('MINIO_ENDPOINT') }}"
        s3_access_key_id: "{{ env_var('MINIO_ROOT_USER') }}"
        s3_secret_access_key: "{{ env_var('MINIO_ROOT_PASSWORD') }}"
        s3_use_ssl: false
        s3_url_style: path

  target: dev
